### ISSUE TITLE
Extracted music seems to be cut in length

### ISSUE THREAD

**Issue by sclsj** [showermat/thplay#2]
e.g. th075_34: Broken Moon
ffprobe /volumes/Seagate\ 5T\ \(Joy\ Jin\)/touhou/th075/TH075_34.flac 
Input #0, flac, from '/volumes/Seagate 5T (Joy Jin)/touhou/th075/TH075_34.flac':
  Metadata:
    Comment         : Processed by SoX
    artist          : ZUN
    album           : 東方萃夢想
    album_eng       : Immaterial and Missing Power
    title           : 砕月
    title_eng       : Broken Moon
    track           : 34
  Duration: 00:00:47.91, start: 0.000000, bitrate: 1086 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16

ffprobe /private/var/root/Desktop/todo\ \(recent\)/黄昏フロンティア-砕月.mp3 
Input #0, mp3, from '/private/var/root/Desktop/todo (recent)/黄昏フロンティア-砕月.mp3':
  Metadata:
    album           : 幻想曲抜萃
    artist          : 黄昏フロンティア
    title           : 砕月
    comment         : 酷我音乐
  Duration: 00:01:45.93, start: 0.011995, bitrate: 320 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s

Notice that the full version I downloaded from a music streaming service (it's the same song) is much longer than the song extracted from the game bgm. 

Am I doing anything wrong? I'm extracting the music because I can't find any lossless album online. I can only find mp3 albums.

**Comment by showermat** [comment]
Have you listened to the longer one all the way through?  Is the second half different from the first half?  Most versions I've found online are at least two repetitions of the song with a little bit extra to fade out at the end, and I think that's what you're seeing.  I checked the specific example you gave, and the intro plus one repetition is 48 seconds long.  It blends seamlessly into the next repetition at the end, so I don't think I made a mistake.  You can tell thplay to dump more than one repetition, if that's what you want.

**Comment by sclsj** [comment]
Ok. I think that's what's happening. Yes, I do remember hearing two identical sections in one song and then a fade out/conclusion for songs from streaming services. Thank you!
